# Numpy

In [5]:
import numpy as np

In [3]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [9]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
array = np.array([[1,2,3],[5,6,7],[7,8,9]])
array

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [14]:
np.zeros_like(array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones_like(array)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.eye(6)  # identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(2,4)

array([[0.28503464, 0.86438114, 0.03018372, 0.44063898],
       [0.25244496, 0.93105353, 0.53558757, 0.69008977]])

In [11]:
np.random.randint(2,4)

3

In [13]:
np.random.random_integers(10,20,(5,4))

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\2765514917.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  np.random.random_integers(10,20,(5,4))


array([[16, 19, 12, 13],
       [10, 14, 17, 12],
       [13, 16, 12, 10],
       [18, 18, 17, 11],
       [13, 13, 16, 14]])

In [ ]:
# Changing the dimension/shape of an array

In [42]:
a = np.arange(6)    # 1D
print(a)          

[0 1 2 3 4 5]


In [47]:
a.reshape(2,3)     # 2D /// 2*3 = 6

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a = np.arange(20)     # 1D
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
a.reshape(5,2,2)     # 3D

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [58]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
# Transpose

a = np.arange(20).reshape(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [66]:
a.T        # Transpose of a matrix

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
# infer

In [14]:
data = np.arange(0,1000).reshape(2,5,50,2)
print(data)

[[[[  0   1]
   [  2   3]
   [  4   5]
   [  6   7]
   [  8   9]
   [ 10  11]
   [ 12  13]
   [ 14  15]
   [ 16  17]
   [ 18  19]
   [ 20  21]
   [ 22  23]
   [ 24  25]
   [ 26  27]
   [ 28  29]
   [ 30  31]
   [ 32  33]
   [ 34  35]
   [ 36  37]
   [ 38  39]
   [ 40  41]
   [ 42  43]
   [ 44  45]
   [ 46  47]
   [ 48  49]
   [ 50  51]
   [ 52  53]
   [ 54  55]
   [ 56  57]
   [ 58  59]
   [ 60  61]
   [ 62  63]
   [ 64  65]
   [ 66  67]
   [ 68  69]
   [ 70  71]
   [ 72  73]
   [ 74  75]
   [ 76  77]
   [ 78  79]
   [ 80  81]
   [ 82  83]
   [ 84  85]
   [ 86  87]
   [ 88  89]
   [ 90  91]
   [ 92  93]
   [ 94  95]
   [ 96  97]
   [ 98  99]]

  [[100 101]
   [102 103]
   [104 105]
   [106 107]
   [108 109]
   [110 111]
   [112 113]
   [114 115]
   [116 117]
   [118 119]
   [120 121]
   [122 123]
   [124 125]
   [126 127]
   [128 129]
   [130 131]
   [132 133]
   [134 135]
   [136 137]
   [138 139]
   [140 141]
   [142 143]
   [144 145]
   [146 147]
   [148 149]
   [150 151]
   [152 15

In [ ]:
# convert it into 2 dim such that number of rows should be 50

In [70]:
data.reshape(50,-1)    # infer

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [15]:
data.reshape(2,5,-1)  # infer

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
          96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
         160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
    

In [ ]:
# Flatten/Ravel --> Converts any higher dimension matrix to one dimension matrix

In [17]:
a = np.arange(20).reshape(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [18]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Basic operation with array

In [20]:
a = np.array([10,20,30,40])
b = np.array([5,3,8,9])

In [21]:
a+b

array([15, 23, 38, 49])

In [22]:
a-b

array([ 5, 17, 22, 31])

In [23]:
a*b

array([ 50,  60, 240, 360])

In [24]:
a/b

array([2.        , 6.66666667, 3.75      , 4.44444444])

In [26]:
a%2

array([0, 0, 0, 0], dtype=int32)

In [27]:
a>15

array([False,  True,  True,  True])

In [28]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [29]:
a = np.array([10,20,30,40,7])
b = np.array([5,3,8,9])

a+b      # while doing any operations with a matrix make sure that both the matix has the same shape.

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# matrix multiplication / dot product

a = n*p
b = p*m
c = n*m

In [31]:
array_1 = np.array([[1,2,3] , [4,5,6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
array_2 = np.array([[1,2,3] , [4,5,6] , [5,6,7]])
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [33]:
array_1.shape

(2, 3)

In [34]:
array_2.shape

(3, 3)

In [75]:
array_1.dot(array_2)   # dot product

array([[24, 30, 36],
       [54, 69, 84]])

In [ ]:
# Unary Operation

In [36]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [37]:
array.sum()   # sum of all the elements

57

In [38]:
array.max()

8

In [39]:
array.min()

2

In [40]:
array.mean()

4.75

In [43]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [ ]:
# axis --> 0 --> column wise
# axis --> 1 --> rowise

In [44]:
array.sum(axis = 0)

array([20, 20, 17])

In [46]:
array.sum(axis = 1)

array([15, 12, 18, 12])

In [47]:
array.min(axis = 0)

array([4, 3, 2])

In [49]:
array.mean(axis = 1)

array([5., 4., 6., 4.])

In [ ]:
# Indexing and slicing with array

In [50]:
# Indexing with 1D array

a = np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [51]:
a[-1]

9

In [52]:
a[2]

5

In [82]:
# indexing with 2D array

array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [86]:
array[2,1]

8

In [87]:
array[1,2]

2

In [53]:
# Slicing in 1D

a = np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [56]:
a[-6:-3:-1]

array([], dtype=int32)

In [90]:
a[0:6:2]

array([3, 5, 7])

In [91]:
# Slicing in 2D

array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [61]:
array[1:3,1:]

array([[3, 2],
       [8, 6]])

In [124]:
a = np.arange(0,25)*23
array = a.reshape(5,5)
array

array([[  0,  23,  46,  69,  92],
       [115, 138, 161, 184, 207],
       [230, 253, 276, 299, 322],
       [345, 368, 391, 414, 437],
       [460, 483, 506, 529, 552]])

In [125]:
array[2:4,1:4]

array([[253, 276, 299],
       [368, 391, 414]])

In [129]:
array[1:4:2,1:4:2]

array([[138, 184],
       [368, 414]])

In [132]:
array[1::3,1::3]

array([[138, 207],
       [483, 552]])

In [ ]:
# Iteration

In [133]:
array = np.array([4,5,6,7])

In [134]:
for i in array:
    print(i)

4
5
6
7


In [137]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
for i in array:
    print(i)

[4 5 6]
[7 3 2]
[4 8 6]
[5 4 3]


In [138]:
for i in array.flatten():
    print(i)

4
5
6
7
3
2
4
8
6
5
4
3
