In [1]:
import numpy as np

In [2]:
#3. linspace

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [4]:
#4 zeros

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
array = np.array([[1,2,3] , [5,6,7] , [7,8,9]])
array

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [9]:
array.shape

(3, 3)

In [7]:
np.zeros_like(array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# 5. ones

np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones_like(array)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
# 6. eye - indentity matrix
"""
diagonal is 1
square - rows = columns
"""

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
# random
np.random.randn(4,5)

array([[-0.35469261,  0.79853305,  1.73679915, -2.07015518,  2.18474057],
       [ 1.22758611, -1.95702556,  0.30076942, -1.45607393,  0.09431256],
       [ 0.11264875,  0.83928339, -0.68928303, -0.19270417, -1.59837777],
       [-0.09934559, -0.18368156, -1.24446688,  0.06608352, -0.74950609]])

In [24]:
np.linalg.inv()

LinAlgError: Singular matrix

In [25]:
np.random.random_integers(10,20,(5,10))

/var/folders/tz/1bkg3flj25ld_mcgv99ct6w80000gn/T/ipykernel_81630/2754271568.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  np.random.random_integers(10,20,(5,10))


array([[10, 12, 15, 13, 16, 12, 20, 11, 20, 12],
       [17, 18, 15, 11, 11, 11, 12, 10, 11, 12],
       [16, 12, 20, 13, 19, 12, 13, 12, 15, 19],
       [16, 19, 17, 20, 18, 11, 19, 17, 16, 13],
       [18, 18, 20, 17, 18, 10, 13, 15, 17, 11]])

In [ ]:
# Changing the dimesnion/shape of an array

Reshape

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
1d - 2d

- dimesnion = the number of elem

In [ ]:
3,2
2,3
6,1
1,6

In [28]:
a.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [30]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
1d - 3d

1,4,5
1,5,4
2,2,5
2,5,2
5,2,2
1,10,2
10,2,1
4,5,1

In [32]:
a.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [34]:
# transpose

data = np.arange(0,20).reshape(5,4)
data , data.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 (5, 4))

In [35]:
data.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
# infer

In [36]:
data = np.arange(0,786).reshape(2,5,50,2)

In [37]:
data

array([[[[  0,   1],
         [  2,   3],
         [  4,   5],
         [  6,   7],
         [  8,   9],
         [ 10,  11],
         [ 12,  13],
         [ 14,  15],
         [ 16,  17],
         [ 18,  19],
         [ 20,  21],
         [ 22,  23],
         [ 24,  25],
         [ 26,  27],
         [ 28,  29],
         [ 30,  31],
         [ 32,  33],
         [ 34,  35],
         [ 36,  37],
         [ 38,  39],
         [ 40,  41],
         [ 42,  43],
         [ 44,  45],
         [ 46,  47],
         [ 48,  49],
         [ 50,  51],
         [ 52,  53],
         [ 54,  55],
         [ 56,  57],
         [ 58,  59],
         [ 60,  61],
         [ 62,  63],
         [ 64,  65],
         [ 66,  67],
         [ 68,  69],
         [ 70,  71],
         [ 72,  73],
         [ 74,  75],
         [ 76,  77],
         [ 78,  79],
         [ 80,  81],
         [ 82,  83],
         [ 84,  85],
         [ 86,  87],
         [ 88,  89],
         [ 90,  91],
         [ 92,  93],
         [ 94

In [ ]:
# convert it into 2 dim such that number of rows should be 50
data.reshape(50,-1)

In [38]:
data.reshape(-1,2)

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27],
       [ 28,  29],
       [ 30,  31],
       [ 32,  33],
       [ 34,  35],
       [ 36,  37],
       [ 38,  39],
       [ 40,  41],
       [ 42,  43],
       [ 44,  45],
       [ 46,  47],
       [ 48,  49],
       [ 50,  51],
       [ 52,  53],
       [ 54,  55],
       [ 56,  57],
       [ 58,  59],
       [ 60,  61],
       [ 62,  63],
       [ 64,  65],
       [ 66,  67],
       [ 68,  69],
       [ 70,  71],
       [ 72,  73],
       [ 74,  75],
       [ 76,  77],
       [ 78,  79],
       [ 80,  81],
       [ 82,  83],
       [ 84,  85],
       [ 86,  87],
       [ 88,  89],
       [ 90,  91],
       [ 92,  93],
       [ 94,  95],
       [ 96,  97],
       [ 98,  99],
       [100, 101],
       [102, 103],
       [104,

In [40]:
data.reshape(2,-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
# FLATTEN/RAVEL

In [ ]:
# convert any higer dimension matrix to 1 dimension matrix

In [41]:
data = np.arange(0,20).reshape(5,4)

In [42]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
data.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
data.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# basic operation with arrays 

(elementwise)

In [45]:
a = np.array([10,20,30,40])
b = np.array([5,3,8,9])

In [46]:
a+b

array([15, 23, 38, 49])

In [47]:
a-b

array([ 5, 17, 22, 31])

In [48]:
a*b

array([ 50,  60, 240, 360])

In [49]:
a/b

array([2.        , 6.66666667, 3.75      , 4.44444444])

In [50]:
a%2

array([0, 0, 0, 0])

In [51]:
a

array([10, 20, 30, 40])

In [52]:
a>15

array([False,  True,  True,  True])

In [53]:
a**2

array([ 100,  400,  900, 1600])

In [54]:
a = np.array([10,20,30,40,7])
b = np.array([5,3,8,9])

In [55]:
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# note - while doing any operation with a matrix make sure that both the matrix has the same shape

In [ ]:
# matrix mul / dot product

In [ ]:
a = n*p
b = p*m
c = n*m

In [56]:
array_1 = np.array([[1,2,3] , [4,5,6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
array_2 = np.array([[1,2,3] , [4,5,6] , [5,6,7]])
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [58]:
array_1.shape

(2, 3)

In [59]:
array_2.shape

(3, 3)

In [60]:
array_1.dot(array_2)

array([[24, 30, 36],
       [54, 69, 84]])

In [ ]:
# unary operation

In [61]:
array = np.array([4,5,6,7,3,2,4])

In [62]:
# sum of all the elememts
array.sum()

31

In [63]:
array.min()

2

In [64]:
array.max()

7

In [65]:
array.mean()

4.428571428571429

In [66]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)

In [67]:
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [68]:
array.sum()

57

In [69]:
"""
axis - 0 - column wise
axis - 1 - rowise

"""

array.sum(axis = 1)

array([15, 12, 18, 12])

In [70]:
array.sum(axis = 0)

array([20, 20, 17])

In [71]:
array.max(axis = 0)

array([7, 8, 6])

In [72]:
array.min(axis = 0)

array([4, 3, 2])

In [74]:
array.mean(axis = 0)

array([5.  , 5.  , 4.25])

In [ ]:
# Indexing and Slicing with array

In [ ]:
# indexing with 1 dim

In [75]:
a = np.arange(3,10)

In [76]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [77]:
a[-1]

9

In [78]:
a[2]

5

In [79]:
# indexing with 2 dim

array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [81]:
array[2][1]

8

In [82]:
array[2,1]

8

In [83]:
array[1,2]

2

In [85]:
# slicing in 1 dim
a = np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [86]:
a[-6:-3:-1]

array([], dtype=int64)

In [87]:
a[0:6:2]

array([3, 5, 7])

In [88]:
# slicing in 2 dim
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

array([[4, 5, 6],
       [7, 3, 2],
       [4, 8, 6],
       [5, 4, 3]])

In [ ]:
3 2
8 6

In [89]:
array[1:3,1:]

array([[3, 2],
       [8, 6]])

In [95]:
a = np.arange(0,25)*23
array = a.reshape(5,5)

In [96]:
array

array([[  0,  23,  46,  69,  92],
       [115, 138, 161, 184, 207],
       [230, 253, 276, 299, 322],
       [345, 368, 391, 414, 437],
       [460, 483, 506, 529, 552]])

In [97]:
array[2:4,1:4]

array([[253, 276, 299],
       [368, 391, 414]])

In [98]:
array[1:4:2,1:4:2]

array([[138, 184],
       [368, 414]])

In [100]:
array[1::3,1::3]

array([[138, 207],
       [483, 552]])

In [ ]:
115, 138, 161, 184, 207
460, 483, 506, 529, 552

In [ ]:
# Iteration

In [ ]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
array

In [102]:
array = np.array([4,5,6,7])

In [103]:
for i in array:
    print(i)

4
5
6
7


In [104]:
array = np.array([4,5,6,7,3,2,4,8,6,5,4,3]).reshape(4,3)
for i in array:
    print(i)

[4 5 6]
[7 3 2]
[4 8 6]
[5 4 3]


In [105]:
for i in array:
    for j in i:
        print(j)

4
5
6
7
3
2
4
8
6
5
4
3


In [106]:
for i in array.flatten():
    print(i)

4
5
6
7
3
2
4
8
6
5
4
3
