In [ ]:
'''
.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Word Character (a-z, A-Z, 0-9, _)
\W      - Not a Word Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (space, tab, newline)

\b      - Word Boundary
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String

[]      - Matches Characters in brackets
[^ ]    - Matches Characters NOT in brackets
|       - Either Or
( )     - Group

Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,4}   - Range of Numbers (Minimum, Maximum)


#### Sample Regexs ####

[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+

'''

In [9]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan\nkhan11.com
afsaan
321-555-4321
123.555.123
123*555*-1234
123.555.123456
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
afsaan
'''

In [1]:
import re

In [ ]:
# extract all the phone numbers with the pattern nnn.nnn.nnnn

In [7]:
search = re.compile(r'\d\d\d\.\d\d\d\.\d\d\d\d')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(196, 208), match='123.555.1234'>
<re.Match object; span=(224, 236), match='123.555.1234'>


In [8]:
# {3}     - Exact Number

search = re.compile(r'\d{3}.\d{3}\.\d{4}')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(196, 208), match='123.555.1234'>
<re.Match object; span=(224, 236), match='123.555.1234'>


In [10]:
# {3,6}     - min and max

search = re.compile(r'\d{3}.\d{3}\.\d{3,6}')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(196, 207), match='123.555.123'>
<re.Match object; span=(222, 236), match='123.555.123456'>


In [ ]:
# extract all the phone numbers with the pattern nnn.nnn.nnnn/nnn-nnn-nnn

In [12]:
# []      - Matches Characters in brackets

search = re.compile(r'[ab]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(82, 83), match='a'>
<re.Match object; span=(85, 86), match='a'>
<re.Match object; span=(87, 88), match='a'>
<re.Match object; span=(92, 93), match='a'>
<re.Match object; span=(95, 96), match='a'>
<re.Match object; span=(97, 98), match='a'>
<re.Match object; span=(113, 114), match='b'>
<re.Match object; span=(119, 120), match='a'>
<re.Match object; span=(156, 157), match='a'>
<re.Match object; span=(158, 159), match='a'>
<re.Match object; span=(161, 162), match='a'>
<re.Match object; span=(162, 163), match='a'>
<re.Match object; span=(167, 168), match='a'>
<re.Match object; span=(176, 177), match='a'>
<re.Match object; span=(179, 180), match='a'>
<re.Match object; span=(180, 181), match='a'>
<re.Match object; span=(270, 271), match='a'>
<re.Match object; span=(288, 289), match='a'>
<re.Match object; span=(300, 301), match='b'>
<re.Match object; span=(322, 323), match='a'>
<re.Matc

In [13]:
search = re.compile(r'[cat]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(82, 83), match='a'>
<re.Match object; span=(85, 86), match='a'>
<re.Match object; span=(87, 88), match='a'>
<re.Match object; span=(91, 92), match='t'>
<re.Match object; span=(92, 93), match='a'>
<re.Match object; span=(95, 96), match='a'>
<re.Match object; span=(97, 98), match='a'>
<re.Match object; span=(98, 99), match='c'>
<re.Match object; span=(99, 100), match='t'>
<re.Match object; span=(110, 111), match='t'>
<re.Match object; span=(118, 119), match='c'>
<re.Match object; span=(119, 120), match='a'>
<re.Match object; span=(156, 157), match='a'>
<re.Match object; span=(158, 159), match='a'>
<re.Match object; span=(161, 162), match='a'>
<re.Match object; span=(162, 163), match='a'>
<re.Match object; span=(167, 168), match='a'>
<re.Match object; span=(172, 173), match='c'>
<re.Match object; span=(176, 177), match='a'>
<re.Match objec

In [ ]:
# extract all the phone numbers with the pattern nnn.nnn.nnnn/nnn-nnn-nnn

In [14]:
search = re.compile(r'\d{3}[.-]\d{3}[.-]\d{3,6}')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(183, 195), match='321-555-4321'>
<re.Match object; span=(196, 207), match='123.555.123'>
<re.Match object; span=(222, 236), match='123.555.123456'>
<re.Match object; span=(237, 249), match='800-555-1234'>
<re.Match object; span=(250, 262), match='900-555-1234'>


In [ ]:
significance of - between numbers and alphabets

In [17]:
search = re.compile(r'[19-]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(59, 60), match='1'>
<re.Match object; span=(60, 61), match='-'>
<re.Match object; span=(64, 65), match='-'>
<re.Match object; span=(68, 69), match='1'>
<re.Match object; span=(70, 71), match='1'>
<re.Match object; span=(78, 79), match='9'>
<re.Match object; span=(169, 170), match='1'>
<re.Match object; span=(170, 171), match='1'>
<re.Match object; span=(185, 186), match='1'>
<re.Match object; span=(186, 187), match='-'>
<re.Match object; span=(190, 191), match='-'>
<re.Match object; span=(194, 195), match='1'>
<re.Match object; span=(196, 197), match='1'>
<re.Match object; span=(204, 205), match='1'>
<re.Match object; span=(208, 209), match='1'>
<re.Match object; span=(216, 217), match='-'>
<re.Match object; span=(217, 218), match='1'>
<re.Match object; span=(222, 223), match='1'>
<re.Match object; span=(230, 231), match='1'>
<re.Match object; span=(240, 241), match='-'>
<re.Match object; span=(244, 245), match='-'>
<re.Match object; span=(245, 246), match='1'>


In [ ]:
how we will extract 555*-1234 using \d\d\d*-\d\d\d\d

In [22]:
search = re.compile(r'[]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(54, 55), match='\\'>
<re.Match object; span=(126, 127), match='.'>
<re.Match object; span=(146, 147), match='\\'>
<re.Match object; span=(171, 172), match='.'>
<re.Match object; span=(199, 200), match='.'>
<re.Match object; span=(203, 204), match='.'>
<re.Match object; span=(225, 226), match='.'>
<re.Match object; span=(229, 230), match='.'>
<re.Match object; span=(265, 266), match='.'>
<re.Match object; span=(296, 297), match='.'>
<re.Match object; span=(309, 310), match='.'>


In [23]:
search=re.compile(r'\d{3}[*.-]\d{3}[*.-]\d{4}')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(183, 195), match='321-555-4321'>
<re.Match object; span=(222, 234), match='123.555.1234'>
<re.Match object; span=(237, 249), match='800-555-1234'>
<re.Match object; span=(250, 262), match='900-555-1234'>


In [25]:
# [^] - matches char not in the bracket
search=re.compile(r'[^abc]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.Match object; span=(24, 25), match='x'>
<re.Match object; span=(25, 26), match='y'>


In [27]:
data = 'cat mat bat sat dat lat can'
search=re.compile(r'[^b]at')
data = search.finditer(data)
for match in data:
    print(match)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(4, 7), match='mat'>
<re.Match object; span=(12, 15), match='sat'>
<re.Match object; span=(16, 19), match='dat'>
<re.Match object; span=(20, 23), match='lat'>


In [28]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan\nkhan11.com
afsaan
321-555-4321
123.555.123
123*555*-1234
123.555.123456
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [30]:
# step1
search=re.compile(r'M')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(89, 90), match='M'>
<re.Match object; span=(263, 264), match='M'>
<re.Match object; span=(275, 276), match='M'>
<re.Match object; span=(284, 285), match='M'>
<re.Match object; span=(293, 294), match='M'>
<re.Match object; span=(307, 308), match='M'>
<re.Match object; span=(313, 314), match='M'>


In [31]:
# step2
search=re.compile(r'Mr')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 265), match='Mr'>
<re.Match object; span=(275, 277), match='Mr'>
<re.Match object; span=(293, 295), match='Mr'>
<re.Match object; span=(307, 309), match='Mr'>
<re.Match object; span=(313, 315), match='Mr'>


In [32]:
# step3
search=re.compile(r'Mr\.')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 266), match='Mr.'>
<re.Match object; span=(307, 310), match='Mr.'>


In [34]:
print(text_to_search)


abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan
khan11.com
afsaan
321-555-4321
123.555.123
123*555*-1234
123.555.123456
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello



In [35]:
# step4
search=re.compile(r'Mr\. ')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 267), match='Mr. '>
<re.Match object; span=(307, 311), match='Mr. '>


In [36]:
# step5
search=re.compile(r'Mr\. [A-Z]')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 268), match='Mr. S'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [37]:
# step6 - 1 and more - +
search=re.compile(r'Mr\. [A-Z][a-z]+')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>


In [38]:
# step7 - 0 and more - *
search=re.compile(r'Mr\. [A-Z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [39]:
search=re.compile(r'Mr\. [A-Z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [41]:
print(text_to_search)


abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan
khan11.com
afsaan
321-555-4321
123.555.123
123*555*-1234
123.555.123456
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello



In [42]:
# step 8
search=re.compile(r'Mr\.? [A-Z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(275, 283), match='Mr Smith'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [44]:
# step 9
search=re.compile(r'M[rs]\.? [A-Z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(275, 283), match='Mr Smith'>
<re.Match object; span=(284, 292), match='Ms Davis'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [50]:
search=re.compile(r'M(r|rs|s)\.? [A-Z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(275, 283), match='Mr Smith'>
<re.Match object; span=(284, 292), match='Ms Davis'>
<re.Match object; span=(293, 306), match='Mrs. Robinson'>
<re.Match object; span=(307, 312), match='Mr. T'>


In [67]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
khanafsaan\nkhan11.com
afsaan
321-555-4321
123.555.123
123*555*-1234
123.555.123456
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [71]:
search=re.compile(r'M(rs|r|s)(\.|_)?[\s]?[A-z][a-z]*')
data = search.finditer(text_to_search)
for match in data:
    print(match)

<re.Match object; span=(263, 274), match='Mr. Schafer'>
<re.Match object; span=(275, 283), match='Mr Smith'>
<re.Match object; span=(284, 292), match='Ms Davis'>
<re.Match object; span=(293, 306), match='Mrs. Robinson'>
<re.Match object; span=(307, 312), match='Mr. T'>
<re.Match object; span=(313, 321), match='Mr_hello'>


# numpy

In [ ]:
- numerical python
- wriiten in c
- fast
- python package used for computation and processing of single / multi dimnsion array
- provides convient and efficeint way to handle large amount data

In [ ]:
# Create a array

In [72]:
import numpy as np

In [74]:
# 1. list/tuple

a = [1,2,3,4,5]
data = np.array(a)
print(data , type(data))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [75]:
a = 1,2,3,4,5
data = np.array(a)
print(data , type(data))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [76]:
a = [[1,2],[3,4],[5,6]]
data = np.array(a)
print(data , type(data))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [79]:
# attributes

#size - count of elements
print(data.size)

#shape - it tells the shape of an array - tuple
print(data.shape)

#ndim - it tells the dim of an array
print(data.ndim)

6
(3, 2)
2


In [80]:
# 2. arange function

np.arange(0,10,3)

array([0, 3, 6, 9])

In [81]:
list(range(0,10,3))

[0, 3, 6, 9]